language: ruby
rvm:
- 2.2.2
branches:
  only:
  - source
install:
- bundle install
- gem install jgd
script:
- jgd -u https://github.com/mnirfan/mnirfan.github.io.git --branch master --branch-from source
