language: ruby
rvm:
- 2.2.2
branches:
  only:
  - source

before_install:
- git config --global user.email "nuhackerz@gmail.com"
- git config --global user.name "nurul irfan"

install:
- bundle install
- gem install jgd
script:
- jgd -u https://github.com/mnirfan/mnirfan.github.io.git --branch master --branch-from source
